"""initial

Revision ID: e90ddeda6fa7
Revises: None
Create Date: 2016-11-03 17:40:35.565980

"""

# revision identifiers, used by Alembic.
revision = 'e90ddeda6fa7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index('ix_timestamp_event_type', 'logs', ['timestamp', 'event_type'], unique=False)
    op.create_table('policies',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=150), nullable=True),
    sa.Column('functions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=True),
    sa.Column('usertype', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('address_country', sa.String(length=30), nullable=True),
    sa.Column('otp', sa.String(length=255), nullable=True),
    sa.Column('otp_expire', sa.DateTime(), nullable=True),
    sa.Column('active_until', sa.DateTime(), nullable=True),
    sa.Column('ins_timestamp', sa.DateTime(), nullable=True),
    sa.Column('upd_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_expire_otp', 'users', ['otp_expire', 'otp'], unique=False)
    op.create_index(op.f('ix_users_active_until'), 'users', ['active_until'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_active_until'), table_name='users')
    op.drop_index('ix_otp_expire_otp', table_name='users')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_index('ix_timestamp_event_type', table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_table('logs')
    ### end Alembic commands ###
